# Generated by Django 3.0.5 on 2020-04-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('parent_subject', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('term', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='subject_kari',
            field=models.CharField(default=10, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='subject_kasi',
            field=models.CharField(default=10, max_length=128),
            preserve_default=False,
        ),
    ]
