# Generated by Django 3.0.5 on 2020-04-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200423_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(default='borrow', max_length=128),
            preserve_default=False,
        ),
    ]
